[package]
name = "zip-targets"
version = "0.0.0"
publish = false

[dependencies]
zip = { git = "https://github.com/mvdnes/zip-rs" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

[[bin]]
name = "read"
path = "read.rs"
