[package]
name = "patch-targets"
version = "0.0.0"
publish = false

[dependencies]
patch = { git = "https://github.com/uniphil/patch-rs" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

[[bin]]
name = "read_patch"
path = "read_patch.rs"
