[package]
name = "html5ever-targets"
version = "0.0.0"
publish = false

[dependencies]
tendril = "0.2.2"
html5ever = { git = "https://github.com/servo/html5ever" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

[[bin]]
name = "read_html"
path = "read_html.rs"
