[package]
name = "fuzz-targets-libfuzzer"
version = "0.1.0"
authors = ["Paul Grandperrin <paul.grandperrin@gmail.com>"]

[dependencies]
fuzz-targets-common = {path = "../common"}
libfuzzer-sys = {git = "https://github.com/rust-fuzz/libfuzzer-sys.git"}