[package]
name = "xml-rs-targets"
version = "0.0.0"
publish = false

[dependencies]
xml-rs = { git = "https://github.com/netvl/xml-rs.git" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

[[bin]]
name = "read_xml"
path = "read_xml.rs"
