[package]
name = "rustfmt-targets"
version = "0.1.0"
publish = false

[dependencies]
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }
rustfmt-nightly = { git = "https://github.com/rust-lang-nursery/rustfmt" }

[[bin]]
name = "fmt"
path = "fmt.rs"
