backspace = "a \b backspace char"
tab = "a \t tab char"
newline = "a \n new line char"
formfeed = "a \f form feed char"
carriage = "a \r carriage return char"
quote = "a \" quote char"
backslash = "a \\ backslash char"
notunicode1 = "no \\u escape"
notunicode2 = "no \u005Cu escape"
notunicode3 = "no \\u0075 escape"
notunicode4 = "no \\\u0075 escape"
