[package]
name = "fuzz-targets-common"
version = "0.1.0"
authors = ["Paul Grandperrin <paul.grandperrin@gmail.com>"]

[dependencies]
brotli = { git = "https://github.com/dropbox/rust-brotli" }
chrono = {git = "https://github.com/chronotope/chrono" }
httparse = { git = "https://github.com/seanmonstar/httparse" }
iso8601 = { git = "https://github.com/badboy/iso8601" }
proc-macro2 = { git = "https://github.com/alexcrichton/proc-macro2.git" }
regex = { git = "https://github.com/rust-lang-nursery/regex" }
url = { git = "https://github.com/servo/rust-url" }
